# Generated by Django 4.1.1 on 2022-09-26 07:29

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0001_initial'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='thematic_area',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='trainings.ThematicAreaTag', to='trainings.ThematicArea', verbose_name='Thematic Area'),
        ),
    ]
