# Generated by Django 4.1.1 on 2022-09-27 05:40

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0003_alter_content_thematic_area'),
        ('accounts', '0004_alter_account_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainee',
            old_name='persona',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='trainee',
            name='thematic_area',
        ),
        migrations.AddField(
            model_name='contentcreator',
            name='role',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentcreator',
            name='sector',
            field=models.CharField(choices=[('private', 'Private Sector'), ('public', 'Public Sector'), ('ngo', 'NGO')], default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentcreator',
            name='specialization',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='trainings.ThematicAreaTag', to='trainings.ThematicArea', verbose_name='Specialization'),
        ),
        migrations.AddField(
            model_name='trainee',
            name='discipline',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='trainings.ThematicAreaTag', to='trainings.ThematicArea', verbose_name='Discipline'),
        ),
        migrations.AddField(
            model_name='trainee',
            name='ocupation',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainee',
            name='sector',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
